name: Gitleaks Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Gitleaks scan
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source . --exit-code 1 --verbose
